### PR TITLE
Lower TDP on AC to 70W

### PR DESCRIPTION
**Pull request by jackpot51**
This may fix overdraw issues when on AC power, and reduce the chance of overheating. I will thoroughly test with the Ryzen 9 3900 and RTX 2070 tomorrow.

### CODE REVIEW

**Review by crawfxrd — APPROVED** [review]

**Comment by jackpot51** [comment]
I am running a stress test with this.

When the CPU can go all the way to 88W, like it did before, it can go above safe temperatures. With this change, running a stress test I am seeing a maximum of about 95C on the CPU and 85C on the GPU. I do not see any overdraw issues with or without the patch.

**Comment by jackpot51** [comment]
Looks like this will need to detect suspend/resume, or we will need to have a firmware change.

**Comment by jackpot51** [comment]
I added a suspend hook, which negates the need for a firmware change

**Review by jacobgkau — APPROVED** [review]

**Comment by jacobgkau** [comment]
I'm seeing the updated limit before and after suspend/resume. As with prior testing, I'm able to get the current usage to spike up to 68000-69000 and am not seeing any issues caused by that load.

**Pull request merged**
